### ISSUE TITLE
直接运行出错

### ISSUE THREAD

**Issue by crush12132** [Gxy-2001/DataScienceAssignment#1]
您好~这边下了代码尝试换了cookie运行报 列表索引超出范围的错误 请问怎么解决呢

**Comment by Gxy-2001** [comment]
fake userAgent库好像出了点问题
换成这样
User_Agent = UserAgent().chrome

**Comment by Gxy-2001** [comment]
还要改时间和搜索词

**Comment by Gxy-2001** [comment]
res = requests.get(url='https://weibo.cn/search/mblog', params=params, headers=headers)
html = etree.HTML(res.text.encode('utf-8'))
weibos = html.xpath("//div[@class='c' and @id]")
这一块你根据现在的微博改改，有错可能是微博改了实现

**Comment by crush12132** [comment]
好 我试试 谢谢您的回复~

**Comment by Gxy-2001** [comment]
weibo.cn的关键词搜索接口在2021.6.6失效，最近我很忙没办法维护，抱歉
